build: add branch name validation

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -6,6 +6,17 @@ BASIC_YELLOW="\e[0;33m"
 BASIC_CYAN="\e[0;36m"
 ENDCOLOR="\e[0m"
 
+run_branch_name_validation () {
+  echo -e "${BASIC_CYAN}🌿 Validating branch name${ENDCOLOR}"
+  npx validate-branch-name
+  if [[ $? -ne 0 ]]
+  then
+    echo -e "${BASIC_RED}❌ Branch name validation failed!${ENDCOLOR}"
+    echo -e "${BASIC_YELLOW}⚠️ Please change your branch name to follow the required pattern.${ENDCOLOR}"
+    exit 1
+  fi
+}
+
 run_tests () {
   echo -e "${BASIC_CYAN}🧪 Running tests${ENDCOLOR}"
   bun run test
@@ -16,6 +27,8 @@ run_tests () {
     exit 1
   fi
 }
+
+run_branch_name_validation
 
 run_tests
 
